## Resilient Distributed Datasets (RDDs) - Lab

Resilient Distributed Datasets (RDD) are fundamental data structures of Spark. An RDD is, essentially, the Spark representation of a set of data, spread across multiple machines, with APIs to let you act on it. An RDD could come from any datasource, e.g. text files, a database, a JSON file etc.


## Objectives

You will be able to:

* Describe RDDs as fundamental storage units in Spark computing environment
* Create RDDs from Python collections
* Set number of partitions for parallelizing RDDs
* Review an RDD's dependancy graph at different stages of processing. 
* Apply the map(func) transformation to a given function on all elements of an RDD in different partitions
* Use collect() action to trigger the processing stage of spark's lazy evaluation
* Use count() action to calculate the number of elements of a parallelized RDD
* Use filter(func) to filter unwanted data from RDDs
* Develop an understanding of Python's lambda functions for RDDs processing

## What are RDDs? 

To get a better understanding of RDDs, let's break down each one of the components of the acronym RDD:

Resilient: RDDs are considered "resilient" because they have built-in fault tolerance. This means that even if one of the nodes goes offline, RDDs will be able to restore the data. This is already a huge advantage compared to standard storage. If a standard computer dies will performing an operation, all of its memory will be lost in the process. With RDDs, multiple nodes can go offline, and the action will still be held in working memory.

Distributed: The data is contained on multiple nodes of a cluster-computing operation. It is efficiently partitioned to allow for parallelism.

Dataset: The dataset has been * partitioned * across the multiple nodes. 

RDDs are the building block upon which more high level spark operations are based upon. Chances are, if you are performing an action using Spark, the operation involves RDDs. 



Key Characteristics of RDDs:

- Immutable: Once an RDD is created, it cannot be modified.
- Lazily Evaluated: RDDs will not be evaluated until an action is triggered. Essentially, when RDDs are created, they are programmed to perform some action, but that function will not get activated until it is explicitly called. The reason for lazy evaluation is that allows users to organize the actions of their Spark program into smaller actions. It also saves unnecessary computation and memory load.
- In-Memory: The operations in Spark are performed in-memory rather than in the Database. This is what allows Spark to perform fast operations with very large quantities of data.

### RDD Transformations vs Actions

In Spark, we first create a __base RDD__ and then apply one or more transformations to that base RDD following our processing needs. Being immutable means, **once an RDD is created, it cannot be changed**. As a result, **each transformation of an RDD creates a new RDD**. Finally, we can apply one or more **actions** to the RDDs. Spark uses lazy evaluation, so transformations are not actually executed until an action occurs.


<img src="rdd1.png" width=500>

Let's see this behavior through a simple example. In this example, we will perform several actions and transformations on RDDs in order to obtain a better understanding of Spark processing. 

### Create a Python collection 

We need some data to start experimenting with RDDs. Let's create some sample data and see how RDDs handle it. To practice working with RDDs, we're going to use a simple Python list.

- Create a Python list `data` of integers between 1 and 1000. 
- Use the `range()` function to create this list of a length = 1000 (1 - 1000 inclusive). 
- Sanity check : confirm the length of the list

In [14]:
nums = list(range(1,1001))
len(nums)

1000

### Initialize an RDD

To initialize an RDD, first create import `pyspark` and then create a SparkContext.

In [7]:
import pyspark
sc = pyspark.SparkContext('local[*]')

Once you've created the SparkContext, you can use the `parallelize` method to create an rdd. Here, create one with 10 partitions.

In [15]:
rdd = sc.parallelize(nums,numSlices=10)
print(type(rdd))

<class 'pyspark.rdd.RDD'>

Determine how many partitions are being used

In [16]:
rdd.getNumPartitions()

10

### Basic descriptive RDD actions

Let's perform some basic operations on our RDD. In the cell below, use the `count`, `first`, `top`, `collect`

In [17]:
rdd.count()

1000

In [18]:
rdd.first()

1

In [19]:
rdd.top(10)

[1000, 999, 998, 997, 996, 995, 994, 993, 992, 991]

In [20]:
## Note: When you are dealing with big data, this could make your computer crash! It's best to avoid using the collect() method
rdd.collect()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000]

## Map functions

Now let's perform some operations on our simple dataset. To begin with, try a basic operation where each number is multiplied by 2. To make this happen, create a function called `multiply_2` and use the map method to apply it to the RDD.

In [21]:
def multiply_2(num):
    return num * 2

doubled = rdd.map(multiply_2)

In [22]:
doubled.top(10)

[2000, 1998, 1996, 1994, 1992, 1990, 1988, 1986, 1984, 1982]

### Lambda Functions

Note that you can also use lambda functions if you want to quickly perform simple operations on data. Let's create a lambda function that subtracts every value by 5.

In [23]:
doubled_minus_5 = doubled.map(lambda x : x -5)

In [24]:
doubled_minus_5.top(10)

[1995, 1993, 1991, 1989, 1987, 1985, 1983, 1981, 1979, 1977]

## Chaining Methods

Much like pandas, you are able to chain methods with Spark. We can perform all of these operations in one line:

In [25]:
rdd.map(multiply_2).map(lambda x : x - 5).top(10)

[1995, 1993, 1991, 1989, 1987, 1985, 1983, 1981, 1979, 1977]

## RDD hierarchy

We are able to see the full journey of RDDs by looking at their hierarchy.

In [ ]:
doubled_minus_5.histogram

### Map vs. Flatmap

Depending on how you want your data to be outputted, you might want to use flatMap, let's take a look at how it performs operations versus the standard map.

In [30]:
mapped = rdd.map(lambda x: (x, x*2 - 5))
print(mapped.count())
print(mapped.take(10))

1000
[(1, -3), (2, -1), (3, 1), (4, 3), (5, 5), (6, 7), (7, 9), (8, 11), (9, 13), (10, 15)]

In [32]:
flat_mapped = rdd.flatMap(lambda x : (x, x*2 -5 ))
print(flat_mapped.count())
print(flat_mapped.take(10))

2000
[1, -3, 2, -1, 3, 1, 4, 3, 5, 5]

## Reduce

Now it's time to figure out the total revenue from this week's worth of sales. Let's do this with a reduce function.

In [26]:
doubled_minus_5.reduce(lambda x,y :x + y)

996000

In [1]:
import numpy as np

In [3]:
user_ids = np.random.randint(1,200,400)
sales_amount = np.random.random(400) * 100

In [6]:
sales_data = list(zip(user_ids,sales_amount))

### ReducebyKey

In [11]:
rdd_sales = sc.parallelize(sales_data)

total_sales = rdd_sales.reduceByKey(lambda x,y : x +y)

### Sort RDDs

In [13]:
total_sales.sortBy(lambda x: x[1],ascending = False).collect()

[(165, 458.98975237990214),
 (133, 439.08856305957636),
 (69, 428.3338944109911),
 (82, 336.3196107071562),
 (62, 289.34679383793156),
 (148, 284.0000366029162),
 (192, 280.1221011473372),
 (151, 266.7766912861809),
 (177, 266.2609065887784),
 (120, 258.16313828831557),
 (94, 257.70857710806143),
 (33, 251.5445577357754),
 (89, 251.23007854980386),
 (186, 249.22583625623912),
 (57, 248.1605174352525),
 (160, 241.51726688448596),
 (124, 240.40451041132525),
 (121, 233.1886142209236),
 (145, 227.00577425491394),
 (194, 225.28740526902874),
 (38, 223.21825418607338),
 (114, 215.36889589428853),
 (58, 215.03891434551574),
 (79, 212.9645925999117),
 (157, 203.19083113109838),
 (34, 196.37483458219697),
 (140, 190.72394480900638),
 (174, 189.31751506575054),
 (26, 189.13605555066135),
 (9, 187.73252573067214),
 (37, 184.64103026462075),
 (45, 181.98621379595886),
 (95, 179.22901432084262),
 (166, 175.01994845679258),
 (51, 174.79545457918886),
 (3, 174.78103514273494),
 (147, 173.1103203864281),
 (119, 171.13965429479427),
 (88, 166.93617031901096),
 (44, 166.67347713929001),
 (115, 165.19128366358012),
 (128, 162.81471217993447),
 (70, 161.46654085346267),
 (113, 160.06737088670303),
 (66, 158.45779531605965),
 (156, 157.46604812448217),
 (181, 155.3977009536116),
 (35, 150.36263302965642),
 (162, 147.79659063372787),
 (91, 147.7831544290321),
 (8, 146.48900700763267),
 (126, 145.43708520173607),
 (158, 138.32221386101793),
 (107, 138.03333760161587),
 (122, 133.37096121009964),
 (118, 133.34070737585694),
 (16, 131.10058781818947),
 (175, 129.39418771887242),
 (159, 125.1090500329174),
 (164, 122.48797282223268),
 (56, 121.79131410747326),
 (101, 120.80987464290091),
 (53, 120.50506353957844),
 (111, 120.31541684205838),
 (102, 118.74838572184078),
 (141, 118.32935927430785),
 (137, 117.76826808472777),
 (23, 115.78544386056655),
 (189, 115.41755031914731),
 (46, 115.38198925268136),
 (36, 115.15538490955318),
 (152, 113.37061698199904),
 (138, 111.93783186334228),
 (149, 108.70274071726672),
 (167, 108.5572353394468),
 (64, 108.15391858417973),
 (2, 107.75476272003115),
 (155, 107.28973625147572),
 (67, 106.91989729367646),
 (172, 106.89091969621836),
 (39, 105.71207044551518),
 (198, 103.41907326902293),
 (109, 102.50906271447505),
 (41, 101.7326640359962),
 (185, 100.70890545649326),
 (59, 100.41019699698273),
 (108, 99.44593797878474),
 (180, 99.30585667905851),
 (130, 99.24991578560518),
 (97, 96.79657748124455),
 (193, 96.38198775485282),
 (171, 95.7262248907967),
 (13, 95.65220184290374),
 (173, 94.53565720764323),
 (71, 94.02721801859991),
 (80, 93.7683343291413),
 (29, 93.48674202058615),
 (87, 92.03378379128708),
 (190, 90.6738526238359),
 (105, 88.80168387560921),
 (72, 87.42473920263619),
 (18, 85.22373542389143),
 (25, 84.22030565388084),
 (132, 82.47672198267932),
 (168, 80.48388199432817),
 (178, 80.09783044475691),
 (27, 79.85780529622184),
 (196, 78.71114701836038),
 (116, 77.86025709168996),
 (47, 74.35986049690048),
 (17, 72.62909255308882),
 (21, 72.32869264651336),
 (43, 70.49552993367661),
 (42, 69.21186195298263),
 (20, 67.79767911617934),
 (143, 67.58218058802584),
 (106, 66.38562011736138),
 (150, 65.52430069860536),
 (12, 64.60170761472908),
 (110, 60.80891023325164),
 (75, 60.54821791551214),
 (55, 60.388596301909644),
 (6, 60.14643620132804),
 (1, 59.11896562901385),
 (176, 58.89961207233427),
 (65, 58.12186855751872),
 (76, 57.31962433413322),
 (86, 57.06540308959083),
 (183, 57.001827357709054),
 (28, 56.829629286834304),
 (92, 56.53479352343537),
 (48, 56.02088167692658),
 (169, 53.880951941149945),
 (195, 53.691206791431725),
 (184, 49.508822837972424),
 (78, 49.34580564921942),
 (90, 49.24951041567937),
 (60, 44.242440089965285),
 (182, 41.9645576805333),
 (50, 41.538425940435886),
 (129, 39.4573299786829),
 (54, 39.15094306330019),
 (15, 38.32203209028706),
 (81, 38.17825465388228),
 (163, 37.367669799988306),
 (188, 36.82716447246142),
 (61, 34.57113996709285),
 (197, 34.483348811905614),
 (22, 33.82403512393951),
 (134, 30.349560814632515),
 (153, 30.32125186002248),
 (187, 29.53521777162551),
 (14, 25.626512197971895),
 (127, 25.37406134799427),
 (19, 25.01676615373348),
 (139, 23.90488637506771),
 (32, 18.768425783680197),
 (24, 18.643474315865948),
 (11, 16.53549344745948),
 (104, 16.14250574942522),
 (103, 12.34930397111198),
 (68, 11.063071226278709),
 (7, 9.928996715605798),
 (73, 9.925120584388935),
 (135, 8.576419058207819),
 (52, 6.412720451212495),
 (170, 4.435083655704474),
 (93, 3.3164533451974565),
 (49, 2.249713517591112),
 (142, 0.36145014457220626)]

### Transformations

Transformations create a new data set from an existing one by passing each dataset element through a function and returns a new RDD representing the results. In short, creating an RDD from an existing RDD is ‘transformation’.
All transformations in Spark are lazy. They do not compute their results right away. Instead, they just remember the transformations applied to some base data set (e.g. a file). The transformations are only computed when an action requires a result that needs to be returned to the driver program.
A transformationon a RDD that returns another RDD, like map, flatMap, filter, reduceByKey, join, cogroup, etc.

### Actions
Actions return final results of RDD computations. Actions trigger execution using lineage graph to load the data into original RDD and carry out all intermediate transformations and return the final results to the Driver program or writes it ou
t to the file system. An action returns a value (to a Spark driver - the user program).

Here are some of key transformations and actions that we will explore later.
<img src="rdd2.png" width=400>

### Additional Reading

- [The original paper on RDDs](https://cs.stanford.edu/~matei/papers/2012/nsdi_spark.pdf)
- [RDDs in Apache Spark](https://data-flair.training/blogs/create-rdds-in-apache-spark/)
- [Programming with RDDs](https://runawayhorse001.github.io/LearningApacheSpark/rdd.html)

## Summary

In this lesson we went through a brief introduction to RDD creation from a Python collection, setting number of logical partitions for an RDD and extracting lineage and of an RDD in a spark application. We also looked at checking an RDD's id used by spark and setting names for RDDs as an indication of content. Following labs will build upon this knowledge and we shall see how transformations and actions can be applied to RDDs in a distributed setup.